### ISSUE TITLE
Anal core/extended download links are equal

### ISSUE THREAD

**Issue by FredericBlum** [DoReCo/doreco#6] opened 2022-09-17 09:17 UTC
There currently seems to be a misplaced download link for the Anal extended set. Both "Download annotation file" buttons refer to the same page on sharedocs. Also, if you switch between core and extended in the [main page](http://concat.huma-num.fr/languages), you can see that for Anal, the count of speakers and words changes, but not the count for texts, which stays at 23.

**Comment by LuPaschen** [comment] 2022-09-22 18:19
This is in fact the expected behavior for any dataset that (i) has no extended files, and (ii) has at least one file with speaker(s) for which there is no phone-level alignment. The word counts for the core set take into account MAUS speakers only, while the word for the extended set take into account all speakers. And when there are no extended files, the download link for core and extended sets are the same.

**Comment by FredericBlum** [comment] 2022-09-23 09:16
Ok, so that explains the download link and the number of texts. However, there seem to be a two problems with speaker_codes and the core/extended distinction, which partially overlap:

- There are 10 unique spk_code's, all marked as `extended==no` in the metadata file, but two of those are actually two speakers (e.g. `Angkam/Damhring`), so its 12 unique speakers listed in the metadata file, apparently all part of the core set
- additionally, there are the speakers `UNK`, `unknown1`, and `unknown2` in the data, so we get to the 15 in total. They do not appear in the metadata-file
- All values of `core_extended` in the Anal corpus are of value `core`, including the data from the unknown speakers

**Comment by LuPaschen** [comment] 2022-09-26 20:06
- Correct (I'm not sure why this is listed as a problem)
- Non-core speakers within core files never appear in the metadata. This is intended.
- `core_extended` is a file-level category, i.e. if the file belongs to the core set, all values will be `core`, even those that belong to non-core speakers. The latter will not have any entries in the `ph` column though.

**Comment by FredericBlum** [comment] 2022-09-27 06:47
Ok, so the info that they should be excluded comes solely from the `ph`-column. Thanks for the clarification.

It's listed as a (small) problem because the main page says it has 10 speakers, not 12.

**Comment by LuPaschen** [comment] 2022-09-28 17:17
Speaker count numbers for Anal will be fixed with the next update of the database. Thanks for pointing this issue out to us.

**Closed as completed** 2023-01-13 10:29 UTC
